-- 코드를 입력하세요
SELECT # CAR_TYPE, 
    # SUM(DAILY_FEE) as TOTAL_FEE, 
    # COUNT(CAR_TYPE) as CAR_NUM,
    # AVG(DAILY_FEE) as AVERAGE_FEE,
    ROUND(AVG(DAILY_FEE), 0) as AVERAGE_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE 
    CAR_TYPE = 'SUV'

