-- 코드를 입력하세요
select 
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE, 
    PRODUCT_ID, USER_ID, SALES_AMOUNT
from ONLINE_SALE
where 
    YEAR(SALES_DATE) = 2022
    AND MONTH(SALES_DATE) = 3
union all
select 
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE,
    PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
from OFFLINE_SALE
where
    YEAR(SALES_DATE) = 2022
    AND MONTH(SALES_DATE) = 3
order by
    SALES_DATE ASC,
    PRODUCT_ID ASC,
    USER_ID ASC