-- 코드를 입력하세요
select
    UGB.TITLE,
    UGB.BOARD_ID,
    UGR.REPLY_ID,
    UGR.WRITER_ID,
    UGR.CONTENTS,
    DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
from
    USED_GOODS_BOARD UGB
join
    USED_GOODS_REPLY UGR ON UGR.BOARD_ID = UGB.BOARD_ID
where
    YEAR(UGB.CREATED_DATE) = 2022
    AND MONTH(UGB.CREATED_DATE) = 10
order by
    UGR.CREATED_DATE ASC,
    UGB.TITLE ASC